### ISSUE TITLE
Email Address Length

### ISSUE THREAD

**Issue by DaveKlassen** [pensierinmusica/email-check#2]
Do you mind if I ask about why a valid email address is limited to 61 characters? (ie. && email.length < 61). In some locations length limitation is discussed to be 254:

http://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address

**Comment by pensierinmusica** [comment]
Because realistically nobody has an email address longer than 60 characters. If you find any real world example that breaks this rule I'd be glad to reconsider.

Look at it as an optimization: if you ask the library to check an email address that is longer than 60 characters, 99.9999% it means the email doesn't exist. So it can give you the response without wasting time in several round-trip web checks.

Hope this helps to clarify, cheers!
